<?php
namespace App\Services;
use App\Models\Media; use App\Support\BrandContext; use Illuminate\Database\Eloquent\Model; use Illuminate\Http\UploadedFile; use Illuminate\Support\Facades\Storage; use Illuminate\Support\Str; use Illuminate\Validation\ValidationException;
class MediaService {
    private const COLLECTIONS=['App\\Models\\Brand'=>['logo','favicon','hero_desktop','hero_mobile','gallery','og'],'App\\Models\\Page'=>['hero_desktop','hero_mobile','gallery','og'],'App\\Models\\Service'=>['cover','gallery','og'],'App\\Models\\Course'=>['cover','gallery','og']];
    public function __construct(private BrandContext $context){}
    public function store(Model $owner, UploadedFile $file, string $collection, array $attributes=[]): Media { if((int)$owner->brand_id!==$this->context->id() && !($owner instanceof \App\Models\Brand && $owner->id===$this->context->id())) throw ValidationException::withMessages(['brand'=>'Media and content brand must match.']); if(!in_array($collection,self::COLLECTIONS[$owner::class]??[],true))throw ValidationException::withMessages(['collection'=>'Unsupported collection.']); \Illuminate\Support\Facades\Validator::make(['file'=>$file],['file'=>'required|image|mimes:jpeg,png,webp|max:10240'])->validate(); $name=Str::uuid().'.'.$file->guessExtension(); $path=$file->storeAs('brands/'.$this->context->id().'/'.$collection,$name,'public'); [$w,$h]=getimagesize($file->getRealPath())?:[null,null]; return $owner->media()->create(array_merge(['brand_id'=>$this->context->id(),'collection'=>$collection,'disk'=>'public','path'=>$path,'original_filename'=>basename($file->getClientOriginalName()),'mime_type'=>$file->getMimeType(),'file_size'=>$file->getSize(),'width'=>$w,'height'=>$h,'sort_order'=>0,'is_primary'=>false],$attributes)); }
    public function delete(Media $media): void { abort_unless($media->brand_id===$this->context->id(),404); Storage::disk($media->disk)->delete($media->path); foreach($media->variants??[] as $path)Storage::disk($media->disk)->delete($path); $media->delete(); }
}
