<?php
namespace App\Services;
use App\Models\{Brand,Course,HomepageContent,Material,Media,PlantSpecimen,PlantVariety}; use App\Support\BrandContext; use Illuminate\Database\Eloquent\Model; use Illuminate\Http\UploadedFile; use Illuminate\Support\Facades\{DB,Storage,Validator}; use Illuminate\Support\Str; use Illuminate\Validation\ValidationException;
class MediaService {
 private const COLLECTIONS=[Brand::class=>['logo','favicon','og'],HomepageContent::class=>['hero_desktop','hero_mobile','intro','gallery'],Course::class=>['cover','gallery','og'],PlantVariety::class=>['mother','gallery','og'],PlantSpecimen::class=>['specimen','gallery'],Material::class=>['cover','gallery','og']];
 private const VARIANTS=['thumbnail'=>480,'card'=>960,'detail'=>1600];
 public function __construct(private BrandContext $context){}
 public function collectionsFor(Model $owner):array{return self::COLLECTIONS[$owner::class]??[];}
 public function store(Model $owner,UploadedFile $file,string $collection,array $attributes=[]):Media{
  $this->assertOwner($owner);if(!in_array($collection,$this->collectionsFor($owner),true))throw ValidationException::withMessages(['collection'=>'不支援的圖片分類。']);
  Validator::make(['file'=>$file],['file'=>'required|image|mimes:jpeg,png,webp|max:10240'])->validate();$info=@getimagesize($file->getRealPath());if(!$info||$info[0]>12000||$info[1]>12000)throw ValidationException::withMessages(['file'=>'圖片尺寸無效或過大。']);
  $base=(string)Str::uuid();$extension=match($file->getMimeType()){'image/jpeg'=>'jpg','image/png'=>'png','image/webp'=>'webp',default=>throw ValidationException::withMessages(['file'=>'只接受 JPEG、PNG 或 WebP。'])};$dir='brands/'.$this->context->id().'/'.$collection;$original=$dir.'/'.$base.'.'.$extension;$written=[];
  try{Storage::disk('public')->putFileAs($dir,$file,$base.'.'.$extension);$written[]=$original;$variants=$this->variants($file->getRealPath(),$dir,$base,$info[0],$info[1],$written);return DB::transaction(function()use($owner,$collection,$attributes,$file,$info,$original,$variants){$safe=collect($attributes)->only(['alt_text','title','sort_order','is_primary'])->all();if($safe['is_primary']??false)$owner->mediaFor($collection)->update(['is_primary'=>false]);return $owner->media()->create($safe+['brand_id'=>$this->context->id(),'collection'=>$collection,'disk'=>'public','path'=>$original,'original_filename'=>basename($file->getClientOriginalName()),'mime_type'=>$file->getMimeType(),'file_size'=>$file->getSize(),'width'=>$info[0],'height'=>$info[1],'sort_order'=>$safe['sort_order']??((int)$owner->mediaFor($collection)->max('sort_order')+1),'is_primary'=>$safe['is_primary']??false,'variants'=>$variants]);});}catch(\Throwable $e){Storage::disk('public')->delete($written);throw $e;}
 }
 private function variants(string $source,string $dir,string $base,int $width,int $height,array &$written):array{$raw=file_get_contents($source);$image=@imagecreatefromstring($raw);if(!$image)throw ValidationException::withMessages(['file'=>'圖片無法解碼。']);$variants=[];try{foreach(self::VARIANTS as $name=>$target){$newWidth=min($target,$width);$newHeight=max(1,(int)round($height*($newWidth/$width)));$canvas=imagecreatetruecolor($newWidth,$newHeight);imagealphablending($canvas,false);imagesavealpha($canvas,true);imagecopyresampled($canvas,$image,0,0,0,0,$newWidth,$newHeight,$width,$height);ob_start();imagewebp($canvas,null,84);$bytes=ob_get_clean();imagedestroy($canvas);$path=$dir.'/'.$base.'-'.$name.'.webp';Storage::disk('public')->put($path,$bytes);$written[]=$path;$variants[$name]=$path;}}finally{imagedestroy($image);}return $variants;}
 public function update(Media $media,array $data):Media{$this->assertMedia($media);$media->update(collect($data)->only(['alt_text','title'])->all());return $media;}
 public function setPrimary(Media $media):void{$this->assertMedia($media);DB::transaction(function()use($media){Media::where('brand_id',$media->brand_id)->where('mediable_type',$media->mediable_type)->where('mediable_id',$media->mediable_id)->where('collection',$media->collection)->update(['is_primary'=>false]);$media->update(['is_primary'=>true]);});}
 public function reorder(Model $owner,string $collection,array $ids):void{$this->assertOwner($owner);$media=$owner->mediaFor($collection)->whereIn('id',$ids)->get();if($media->count()!==count(array_unique($ids)))throw ValidationException::withMessages(['media'=>'圖片排序資料不正確。']);DB::transaction(fn()=>collect($ids)->each(fn($id,$order)=>Media::whereKey($id)->update(['sort_order'=>$order])));}
 public function delete(Media $media):void{$this->assertMedia($media);$paths=array_merge([$media->path],array_values($media->variants??[]));DB::transaction(fn()=>$media->delete());Storage::disk($media->disk)->delete($paths);}
 private function assertOwner(Model $owner):void{$id=$owner instanceof Brand?$owner->id:$owner->brand_id;if((int)$id!==$this->context->id())throw ValidationException::withMessages(['brand'=>'圖片與內容品牌必須一致。']);}
 private function assertMedia(Media $media):void{if((int)$media->brand_id!==$this->context->id())abort(404);}
}
