<?php
namespace Tests\Feature;
use App\Models\{Brand,BrandLink,Course,Media,Page,Service}; use App\Services\MediaService; use App\Support\BrandContext; use Illuminate\Foundation\Testing\RefreshDatabase; use Illuminate\Http\UploadedFile; use Illuminate\Support\Facades\Schema; use Illuminate\Support\Facades\Storage; use Illuminate\Validation\ValidationException; use Tests\TestCase;
class BrandSiteTest extends TestCase { use RefreshDatabase;
 private function brand(string $slug='verdant',string $domain='brand-a.localhost'): Brand{return Brand::factory()->create(['slug'=>$slug,'domain'=>$domain]);}
 private function page(Brand $b,string $type='home',string $slug='home'): Page{return Page::factory()->create(['brand_id'=>$b->id,'type'=>$type,'slug'=>$slug]);}
 public function test_hostname_resolves_brand_a():void{$a=$this->brand();$this->page($a);$this->get('http://brand-a.localhost/')->assertOk()->assertSee($a->name);}
 public function test_hostname_resolves_brand_b():void{$b=$this->brand('terracotta','brand-b.localhost');$this->page($b);$this->get('http://brand-b.localhost/')->assertOk()->assertSee($b->name);}
 public function test_cross_brand_content_is_isolated():void{$a=$this->brand();$b=$this->brand('terracotta','brand-b.localhost');$this->page($a);$this->page($b);$foreign=Service::factory()->create(['brand_id'=>$b->id,'slug'=>'secret']);$this->withServerVariables(['HTTP_HOST'=>'brand-a.localhost'])->get('/services/'.$foreign->slug)->assertNotFound();}
 public function test_only_currently_published_content_is_visible():void{$b=$this->brand();$this->page($b);Service::factory()->create(['brand_id'=>$b->id,'name'=>'Visible']);Service::factory()->create(['brand_id'=>$b->id,'name'=>'Draft','status'=>'draft']);Service::factory()->create(['brand_id'=>$b->id,'name'=>'Future','published_at'=>now()->addDay()]);$this->withServerVariables(['HTTP_HOST'=>'brand-a.localhost'])->get('/services')->assertSee('Visible')->assertDontSee('Draft')->assertDontSee('Future');}
 public function test_page_service_and_course_support_multiple_media():void{$b=$this->brand();foreach([Page::factory()->create(['brand_id'=>$b->id]),Service::factory()->create(['brand_id'=>$b->id]),Course::factory()->create(['brand_id'=>$b->id])] as $owner){Media::factory()->count(2)->create(['brand_id'=>$b->id,'mediable_type'=>$owner->getMorphClass(),'mediable_id'=>$owner->id]);$this->assertCount(2,$owner->media);}}
 public function test_media_collection_order_and_primary_are_stable():void{$b=$this->brand();$p=$this->page($b);Media::factory()->create(['brand_id'=>$b->id,'mediable_id'=>$p->id,'sort_order'=>2]);$primary=Media::factory()->create(['brand_id'=>$b->id,'mediable_id'=>$p->id,'sort_order'=>1,'is_primary'=>true]);$this->assertSame($primary->id,$p->primaryMedia('gallery')->id);$this->assertSame([1,2],$p->mediaFor('gallery')->pluck('sort_order')->all());}
 public function test_media_service_rejects_cross_brand_owner():void{$a=$this->brand();$b=$this->brand('terracotta','brand-b.localhost');$page=Page::factory()->create(['brand_id'=>$b->id]);app(BrandContext::class)->set($a);$this->expectException(ValidationException::class);app(MediaService::class)->store($page,UploadedFile::fake()->image('leaf.jpg'),'gallery');}
 public function test_content_tables_have_no_image_path_columns():void{foreach(['pages','services','courses'] as $table)foreach(Schema::getColumnListing($table) as $column)$this->assertDoesNotMatchRegularExpression('/^(image|cover|logo|favicon|hero)(_path|_\d+)?$/',$column);}
 public function test_social_links_are_safe_and_rendered():void{$b=$this->brand();$this->page($b);BrandLink::factory()->create(['brand_id'=>$b->id,'label'=>'Instagram']);$this->withServerVariables(['HTTP_HOST'=>'brand-a.localhost'])->get('/')->assertSee('Instagram')->assertSee('noopener noreferrer',false);}
 public function test_missing_image_uses_placeholder_and_unknown_route_is_404():void{$b=$this->brand();$this->page($b);Service::factory()->create(['brand_id'=>$b->id]);$this->withServerVariables(['HTTP_HOST'=>'brand-a.localhost'])->get('/services')->assertSee('圖片準備中');$this->withServerVariables(['HTTP_HOST'=>'brand-a.localhost'])->get('/not-here')->assertNotFound();}
}
