<?php
namespace App\Livewire\Admin;
use App\Models\{Brand,Course,HomepageContent,Material,Media,PlantSpecimen,PlantVariety}; use App\Services\{AuditService,MediaService}; use App\Support\BrandContext; use Illuminate\Database\Eloquent\Model; use Illuminate\Foundation\Auth\Access\AuthorizesRequests; use Livewire\Component; use Livewire\WithFileUploads;
class MediaManager extends Component { use AuthorizesRequests, WithFileUploads; public string $ownerType; public int $ownerId; public string $collection; public array $uploads=[]; public string $alt=''; public bool $primary=false;
 public function mount(string $ownerType,int $ownerId,?string $collection=null):void{$this->ownerType=$ownerType;$this->ownerId=$ownerId;$owner=$this->owner();$this->authorize('view',$owner);$this->collection=$collection?:app(MediaService::class)->collectionsFor($owner)[0];}
 private function owner():Model{$class=['brand'=>Brand::class,'homepage'=>HomepageContent::class,'course'=>Course::class,'plant_variety'=>PlantVariety::class,'plant_specimen'=>PlantSpecimen::class,'material'=>Material::class][$this->ownerType]??abort(404);$query=$class::query();if($class===Brand::class)$query->whereKey(app(BrandContext::class)->id());else$query->where('brand_id',app(BrandContext::class)->id())->whereKey($this->ownerId);return $query->firstOrFail();}
 public function saveUploads(MediaService $service,AuditService $audit):void{$owner=$this->owner();$this->authorize('update',$owner);$this->validate(['uploads'=>'required|array|max:12','uploads.*'=>'image|mimes:jpeg,png,webp|max:10240','collection'=>'required|string','alt'=>'nullable|string|max:255']);foreach($this->uploads as $i=>$file){$media=$service->store($owner,$file,$this->collection,['alt_text'=>$this->alt,'is_primary'=>$this->primary&&$i===0]);$audit->record('media.uploaded',$media,[],$media->toArray());}$this->reset('uploads','alt','primary');session()->flash('status','圖片已上傳。');}
 public function setPrimary(int $id,MediaService $service,AuditService $audit):void{$owner=$this->owner();$this->authorize('update',$owner);$media=$owner->media()->whereKey($id)->firstOrFail();$service->setPrimary($media);$audit->record('media.primary_changed',$media,[],['is_primary'=>true]);}
 public function move(int $id,string $direction,MediaService $service,AuditService $audit):void{$owner=$this->owner();$this->authorize('update',$owner);$ids=$owner->mediaFor($this->collection)->pluck('id')->all();$index=array_search($id,$ids,true);$target=$direction==='up'?$index-1:$index+1;if($index===false||!isset($ids[$target]))return;[$ids[$index],$ids[$target]]=[$ids[$target],$ids[$index]];$service->reorder($owner,$this->collection,$ids);$audit->record('media.reordered',$owner,[],['collection'=>$this->collection,'ids'=>$ids]);}
 public function delete(int $id,MediaService $service,AuditService $audit):void{$owner=$this->owner();$this->authorize('update',$owner);$media=$owner->media()->whereKey($id)->firstOrFail();$before=$media->toArray();$service->delete($media);$audit->record('media.deleted',$owner,$before);}
 public function render(){ $owner=$this->owner();$this->authorize('view',$owner);return view('livewire.admin.media-manager',['owner'=>$owner,'collections'=>app(MediaService::class)->collectionsFor($owner),'media'=>$owner->mediaFor($this->collection)->get()]);}
}
