@extends('layouts.admin')
@section('title','首頁維護')
@section('content')
<div class="admin-heading"><div><p class="admin-kicker">HOMEPAGE</p><h1>首頁維護</h1><p>內容先儲存為草稿，預覽確認後再發布。</p></div><div class="heading-actions"><a class="admin-button secondary" href="{{ route('admin.homepage.preview') }}" target="_blank" rel="noopener noreferrer">預覽草稿</a><form method="post" action="{{ route('admin.homepage.publish') }}">@csrf<button class="admin-button">發布首頁</button></form></div></div>
<form method="post" action="{{ route('admin.homepage.update') }}" class="admin-form">@csrf @method('PUT')
 <details class="admin-panel homepage-card" open><summary><strong>主視覺</strong><span>單張桌機／手機圖片、標題與兩個按鈕</span></summary><div class="homepage-fields"><div class="form-grid"><label>標題<input name="hero_title" value="{{ old('hero_title',data_get($draft,'hero_title')) }}"></label><label>副標題<input name="hero_subtitle" value="{{ old('hero_subtitle',data_get($draft,'hero_subtitle')) }}"></label><label>主要按鈕文字<input name="hero_primary_label" value="{{ old('hero_primary_label',data_get($draft,'hero_primary_label','探索課程')) }}"></label><label>次要按鈕文字<input name="hero_secondary_label" value="{{ old('hero_secondary_label',data_get($draft,'hero_secondary_label','逛逛商店')) }}"></label></div><div class="form-grid"><label>桌機圖片<select name="hero_desktop_media_id"><option value="">未選擇</option>@foreach($homepage->mediaFor('hero_desktop')->get() as $image)<option value="{{ $image->id }}" @selected(old('hero_desktop_media_id',data_get($draft,'hero_desktop_media_id'))==$image->id)>{{ $image->original_filename }}</option>@endforeach</select></label><label>手機圖片<select name="hero_mobile_media_id"><option value="">未選擇</option>@foreach($homepage->mediaFor('hero_mobile')->get() as $image)<option value="{{ $image->id }}" @selected(old('hero_mobile_media_id',data_get($draft,'hero_mobile_media_id'))==$image->id)>{{ $image->original_filename }}</option>@endforeach</select></label></div></div></details>
 <details class="admin-panel homepage-card"><summary><strong>品牌介紹</strong><span>圖片、標題、內容與選填連結</span></summary><div class="homepage-fields"><label>標題<input name="intro_title" value="{{ old('intro_title',data_get($draft,'intro_title')) }}"></label><label>內容<textarea name="intro_body" rows="6">{{ old('intro_body',data_get($draft,'intro_body')) }}</textarea></label><div class="form-grid"><label>圖片<select name="intro_media_id"><option value="">未選擇</option>@foreach($homepage->mediaFor('intro')->get() as $image)<option value="{{ $image->id }}" @selected(old('intro_media_id',data_get($draft,'intro_media_id'))==$image->id)>{{ $image->original_filename }}</option>@endforeach</select></label><label>連結文字<input name="intro_link_label" value="{{ old('intro_link_label',data_get($draft,'intro_link_label')) }}"></label><label>連結網址<input name="intro_link_url" type="url" value="{{ old('intro_link_url',data_get($draft,'intro_link_url')) }}"></label></div></div></details>
 <details class="admin-panel homepage-card"><summary><strong>精選手作課程</strong><span>最多 6 項</span></summary><div class="homepage-fields checks">@forelse($courses as $course)<label class="check"><input type="checkbox" name="featured_course_ids[]" value="{{ $course->id }}" @checked(in_array($course->id,old('featured_course_ids',data_get($draft,'featured_course_ids',[]))))>{{ $course->name }}</label>@empty<p>請先建立課程。</p>@endforelse</div></details>
 <details class="admin-panel homepage-card"><summary><strong>品牌照片輪播</strong><span>標題、簡短文字與選填連結</span></summary><div class="homepage-fields gallery-admin">@forelse($homepage->mediaFor('gallery')->get() as $image)@php($item=collect(data_get($draft,'gallery_items',[]))->firstWhere('media_id',$image->id))<article><img src="{{ $image->url('thumbnail') }}" alt="{{ $image->alt_text }}"><div><label class="check"><input type="checkbox" name="gallery[{{ $image->id }}][enabled]" value="1" @checked($item)> 顯示</label><input name="gallery[{{ $image->id }}][title]" value="{{ old('gallery.'.$image->id.'.title',data_get($item,'title')) }}" placeholder="標題"><input name="gallery[{{ $image->id }}][body]" value="{{ old('gallery.'.$image->id.'.body',data_get($item,'body')) }}" placeholder="簡短文字"><input name="gallery[{{ $image->id }}][url]" type="url" value="{{ old('gallery.'.$image->id.'.url',data_get($item,'url')) }}" placeholder="https://（選填）"></div></article>@empty<p>尚未上傳輪播圖片。</p>@endforelse</div></details>
 <button class="admin-button" type="submit">儲存草稿</button>
</form>
<livewire:admin.media-manager owner-type="homepage" :owner-id="$homepage->id" collection="hero_desktop" />
@endsection
