@extends('layouts.site')
@section('title','填寫收件資料｜'.$brand->name)
@section('content')
<section class="page-hero compact"><p class="eyebrow">ORDER DETAILS</p><h1>填寫收件資料</h1><p>成交單 {{ $order->reference }}</p></section>
<section class="section registration-layout">
<form method="post" action="{{ route('order-recipient.update',[$order->reference,$token]) }}" class="public-form" x-data="{shipping:'{{ old('shipping_method',$order->shipping_method?:'seven_eleven') }}'}">@csrf @method('PUT')
<input class="honeypot" name="company_website" tabindex="-1" autocomplete="off" aria-hidden="true">
<h2>基本資料</h2><div class="form-grid"><label>姓名<input name="customer_name" value="{{ old('customer_name',$order->customer_name) }}" required autocomplete="name"></label><label>手機<input name="phone" value="{{ old('phone',$order->phone) }}" required autocomplete="tel"></label><label>社群平台<select name="social_platform" required><option value="facebook">Facebook</option><option value="instagram">Instagram</option><option value="line">LINE</option><option value="other">其他</option></select></label><label>社群帳號<input name="social_account" value="{{ old('social_account',$order->social_account) }}" required></label></div>
<h2>收件方式</h2><label>配送方式<select name="shipping_method" x-model="shipping" required><option value="seven_eleven">7-11 店到店（NT$ {{ config('commerce.shipping_fees.seven_eleven') }}）</option><option value="family_mart">全家店到店（NT$ {{ config('commerce.shipping_fees.family_mart') }}）</option><option value="postal">郵寄（NT$ {{ config('commerce.shipping_fees.postal') }}）</option><option value="self_pickup">自取（由粉專聯絡約定）</option></select></label>
<div class="form-grid" x-show="shipping==='seven_eleven'||shipping==='family_mart'"><label>店號<input name="store_no" value="{{ old('store_no',data_get($order->shipping_details,'store_no')) }}" :required="shipping==='seven_eleven'||shipping==='family_mart'"></label><label>門市名稱<input name="store_name" value="{{ old('store_name',data_get($order->shipping_details,'store_name')) }}" :required="shipping==='seven_eleven'||shipping==='family_mart'"></label></div>
<div x-show="shipping==='postal'" class="form-grid"><label>郵遞區號<input name="postal_code" value="{{ old('postal_code',data_get($order->shipping_details,'postal_code')) }}" :required="shipping==='postal'"></label><label>縣市<input name="postal_city" value="{{ old('postal_city',data_get($order->shipping_details,'city')) }}" :required="shipping==='postal'"></label><label>區域<input name="postal_district" value="{{ old('postal_district',data_get($order->shipping_details,'district')) }}" :required="shipping==='postal'"></label><label>完整地址<input name="postal_address" value="{{ old('postal_address',data_get($order->shipping_details,'address')) }}" :required="shipping==='postal'"></label></div>
<p x-show="shipping==='self_pickup'">自取時間與地點將由品牌透過粉專另行聯繫。</p><label>匯款帳號末五碼（選填）<input name="remittance_last_five" value="{{ old('remittance_last_five',$order->remittance_last_five) }}" inputmode="numeric" pattern="[0-9]{5}" maxlength="5"></label><label>備註<textarea name="notes" rows="4">{{ old('notes',$order->notes) }}</textarea></label>@if($errors->any())<div class="error-summary"><ul>@foreach($errors->all() as $error)<li>{{ $error }}</li>@endforeach</ul></div>@endif<button class="button">送出收件資料</button></form>
<aside class="bank-card"><h2>商品與金額</h2>@foreach($order->items as $item)<p><strong>{{ $item->product_name }}</strong><br>{{ $item->quantity }} × NT$ {{ number_format((float)$item->unit_price) }}</p>@endforeach<dl class="order-total"><dt>商品小計</dt><dd>NT$ {{ number_format((float)$order->subtotal) }}</dd><dt>運費</dt><dd>@if($order->free_shipping)<s x-text="'NT$ '+({seven_eleven:80,family_mart:80,postal:120,self_pickup:0}[shipping])"></s> 免運費@else<span x-text="'NT$ '+({seven_eleven:80,family_mart:80,postal:120,self_pickup:0}[shipping])"></span>@endif</dd><dt>應付金額</dt><dd x-text="'NT$ '+({{ (float)$order->subtotal }}+({{ $order->free_shipping?'0':'({seven_eleven:80,family_mart:80,postal:120,self_pickup:0}[shipping])' }})).toLocaleString()"></dd></dl><h2>品牌匯款帳戶</h2><x-bank-information :bank="$order->bank_snapshot"/></aside></section>
@endsection
