@extends('layouts.site')
@section('title','線上商店｜'.$brand->name)
@section('content')
<section class="page-hero"><p class="eyebrow">SHOP</p><h1>線上商店</h1><p>瀏覽喜歡的植株與資材，複製商品連結後私訊粉專確認購買。</p></section>
<section class="section" x-data="{tab:'all'}"><div class="shop-tabs" role="tablist" aria-label="商品分類"><button type="button" @click="tab='all'" :class="tab==='all'?'active':''">全部</button><button type="button" @click="tab='plants'" :class="tab==='plants'?'active':''">植株</button><button type="button" @click="tab='materials'" :class="tab==='materials'?'active':''">資材</button></div><div class="product-grid">
@foreach($varieties as $variety)<article class="product-card {{ $variety->availableStock()===0?'sold-out':'' }}" x-show="tab==='all'||tab==='plants'" x-transition><a href="{{ route('shop.plants.show',$variety->slug) }}"><x-media-image :media="$variety->primaryMedia('mother')" /></a><div><p class="meta">植株・在庫 {{ $variety->availableStock() }}</p><h2><a href="{{ route('shop.plants.show',$variety->slug) }}">{{ $variety->name }}</a></h2>@php($prices=$variety->specimens->where('status','published')->where(fn($item)=>$item->availableQuantity()>0)->pluck('price'))<strong>{{ $prices->isNotEmpty()?'NT$ '.number_format((float)$prices->min()).' 起':'售完' }}</strong></div></article>@endforeach
@foreach($materials as $material)<article class="product-card {{ $material->availableQuantity()===0?'sold-out':'' }}" x-show="tab==='all'||tab==='materials'" x-transition><a href="{{ route('shop.materials.show',$material->slug) }}"><x-media-image :media="$material->primaryMedia('cover')" /></a><div><p class="meta">資材・在庫 {{ $material->availableQuantity() }}</p><h2><a href="{{ route('shop.materials.show',$material->slug) }}">{{ $material->name }}</a></h2><strong>{{ $material->availableQuantity()>0?'NT$ '.number_format((float)$material->price):'售完' }}</strong></div></article>@endforeach
@if($varieties->isEmpty()&&$materials->isEmpty())<p class="empty">目前尚無販售中的商品。</p>@endif</div></section>
@if($soldUnits->isNotEmpty())<section class="section sold-section"><div class="section-head"><div><p class="eyebrow">RECENTLY SOLD</p><h2>近期已售出植株</h2></div></div><div class="sold-grid">@foreach($soldUnits as $sold)<article class="product-card sold-out"><a href="{{ route('shop.sold.show',$sold) }}"><x-media-image :media="$sold->specimen?->primaryMedia('specimen')"/></a><div><p class="meta">已售出・{{ $sold->sold_at->format('Y/m/d') }}</p><h3><a href="{{ route('shop.sold.show',$sold) }}">{{ $sold->variety_name_snapshot }}</a></h3><strong>已售出</strong></div></article>@endforeach</div></section>@endif
@endsection
