@extends('layouts.admin')
@section('title',($course->exists?'編輯':'新增').'課程')
@section('content')
<div class="admin-heading"><div><p class="admin-kicker">COURSE</p><h1>{{ $course->exists?'編輯':'新增' }}課程</h1></div><div class="heading-actions">@if($course->exists)<a class="admin-button secondary" href="{{ route('courses.show',$course->slug) }}" target="_blank">前台檢視</a>@endif<a href="{{ route('admin.courses.index') }}">返回列表</a></div></div>
<form method="post" action="{{ $course->exists?route('admin.courses.update',$course):route('admin.courses.store') }}" class="admin-panel admin-form">@csrf @if($course->exists)@method('PUT')@endif
<div class="form-grid"><label>名稱<input name="name" value="{{ old('name',$course->name) }}" required></label><label>Slug<input name="slug" value="{{ old('slug',$course->slug) }}" required pattern="[A-Za-z0-9_-]+"></label><label>課程分鐘數<input type="number" name="duration_minutes" min="1" value="{{ old('duration_minutes',$course->duration_minutes) }}"></label><label>排序<input type="number" name="sort_order" min="0" value="{{ old('sort_order',$course->sort_order??0) }}"></label></div>
<label>列表簡介<textarea name="summary" rows="3">{{ old('summary',$course->summary) }}</textarea></label><label>完整介紹<textarea name="description" rows="10">{{ old('description',$course->description) }}</textarea></label><div class="form-grid"><label>適合對象<textarea name="suitable_for" rows="5">{{ old('suitable_for',$course->suitable_for) }}</textarea></label><label>注意事項／成品說明<textarea name="precautions" rows="5">{{ old('precautions',$course->precautions) }}</textarea></label></div><label>行前通知 Notion URL<input type="url" name="notion_url" value="{{ old('notion_url',$course->notion_url) }}" placeholder="https://....notion.site/..."></label>
@php($defaultPlans=$course->exists?$course->plans->map(fn($p)=>['name'=>$p->name,'participants'=>$p->participants,'price'=>$p->price,'is_enabled'=>$p->is_enabled?1:0])->all():[['name'=>'單人方案','participants'=>1,'price'=>'','is_enabled'=>1]])
<fieldset class="admin-subpanel" x-data="{plans: {{ Js::from(array_values(old('plans',$defaultPlans))) }} }"><legend>預設方案</legend><p>價格以方案計算，不以人頭計算；場次可另行覆寫。</p><template x-for="(plan,index) in plans" :key="index"><div class="repeat-row"><label>名稱<input :name="`plans[${index}][name]`" x-model="plan.name" required></label><label>包含人數<input type="number" min="1" :name="`plans[${index}][participants]`" x-model="plan.participants" required></label><label>方案價格<input type="number" min="0" step="1" :name="`plans[${index}][price]`" x-model="plan.price" required></label><label class="check"><input type="checkbox" value="1" :name="`plans[${index}][is_enabled]`" x-model="plan.is_enabled">啟用</label><button type="button" class="admin-button danger" @click="plans.splice(index,1)" x-show="plans.length>1">移除</button></div></template><button type="button" class="admin-button secondary" @click="plans.push({name:'',participants:1,price:'',is_enabled:1})">新增方案</button></fieldset>
<details><summary>SEO 設定</summary><label>SEO 標題<input name="seo_title" value="{{ old('seo_title',$course->seo_title) }}"></label><label>SEO 說明<textarea name="seo_description" rows="3">{{ old('seo_description',$course->seo_description) }}</textarea></label></details><div class="form-actions"><button class="admin-button">儲存</button></div></form>
@if($course->exists)
<section class="admin-panel"><div class="panel-head"><div><h2>課程場次</h2><p>名額在開放報名後即鎖定。</p></div><a class="admin-button" href="{{ route('admin.course-sessions.create',$course) }}">新增場次</a></div><div class="session-list">@forelse($course->sessions()->with('registrations')->get() as $session)<article><div><strong>{{ $session->starts_at->format('Y/m/d H:i') }}</strong><small>{{ $session->city }}・{{ $session->venue_name }}・剩餘 {{ $session->remainingCapacity() }}</small></div><span class="status {{ $session->status }}">{{ ['draft'=>'草稿','open'=>'開放報名','closed'=>'截止報名','cancelled'=>'已取消'][$session->status] }}</span><a href="{{ route('admin.course-sessions.edit',[$course,$session]) }}">編輯</a></article>@empty<p>尚無場次。</p>@endforelse</div></section>
<div class="publish-actions admin-panel"><div><strong>發布控制</strong><p>發布後，前台才會顯示課程。</p></div>@if($course->status==='published')<form method="post" action="{{ route('admin.courses.unpublish',$course) }}">@csrf<button class="admin-button secondary">下架</button></form>@else<form method="post" action="{{ route('admin.courses.publish',$course) }}">@csrf<button class="admin-button">發布</button></form>@endif<form method="post" action="{{ route('admin.courses.destroy',$course) }}" onsubmit="return confirm('確定刪除？')">@csrf @method('DELETE')<button class="admin-button danger">刪除</button></form></div>
<livewire:admin.media-manager owner-type="course" :owner-id="$course->id" />
@endif
@endsection
