<!doctype html>
<html lang="zh-Hant"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>@yield('title','後台')｜{{ $brand->name }}</title>@vite(['resources/css/app.css','resources/js/app.js'])@livewireStyles<style>:root{--primary:{{ $brand->primary_color }};--secondary:{{ $brand->secondary_color }};--accent:{{ $brand->accent_color }};--bg:#f3f5f4;--text:#18201c}</style></head>
<body class="admin-body" x-data="{nav:false}"><a class="skip" href="#admin-content">跳至主要內容</a>
<aside class="admin-sidebar" :class="nav?'open':''"><a class="admin-logo" href="{{ route('admin.dashboard') }}">✦ Flora Admin</a><p class="sidebar-label">目前品牌</p><strong>{{ $brand->name }}</strong>
 @if(isset($adminBrands)&&$adminBrands->count()>1)<div class="brand-switcher">@foreach($adminBrands as $option)<form method="post" action="{{ route('admin.switch-brand',$option) }}">@csrf<button class="{{ $option->id===$brand->id?'active':'' }}">{{ $option->name }}</button></form>@endforeach</div>@endif
 <nav aria-label="後台導覽"><a href="{{ route('admin.dashboard') }}">總覽</a>@if(auth()->user()->role!=='member')<a href="{{ route('admin.content.index','pages') }}">頁面</a><a href="{{ route('admin.content.index','services') }}">服務</a><a href="{{ route('admin.content.index','courses') }}">課程</a><a href="{{ route('admin.media.index') }}">圖片</a><a href="{{ route('admin.links.index') }}">外部連結</a><a href="{{ route('admin.settings') }}">品牌設定</a>@endif @if(auth()->user()->isSuperAdmin())<span class="sidebar-label">系統管理</span><a href="{{ route('admin.brands.index') }}">品牌</a><a href="{{ route('admin.users.index') }}">使用者</a>@endif</nav>
 <div class="sidebar-bottom"><a href="{{ route('admin.profile') }}">{{ auth()->user()->name }}</a><form method="post" action="{{ route('logout') }}">@csrf<button>登出</button></form></div>
</aside>
<div class="admin-main"><header class="admin-topbar"><button class="admin-menu" @click="nav=!nav" :aria-expanded="nav">選單</button><div><span>{{ auth()->user()->role }}</span><a href="{{ route('home') }}" target="_blank" rel="noopener noreferrer">查看前台 ↗</a></div></header><main id="admin-content" class="admin-content">@if(session('status'))<div class="notice">{{ session('status') }}</div>@endif @if($errors->any())<div class="error-summary" role="alert"><strong>請檢查以下欄位：</strong><ul>@foreach($errors->all() as $error)<li>{{ $error }}</li>@endforeach</ul></div>@endif @yield('content')</main></div>
@livewireScripts</body></html>
