<?php
namespace App\Http\Controllers\Admin;
use App\Http\Controllers\Controller; use App\Models\{Course,Page,Service}; use App\Services\AuditService; use App\Support\BrandContext; use Illuminate\Database\Eloquent\Model; use Illuminate\Http\Request; use Illuminate\Validation\Rule;
class ContentController extends Controller {
 private const MAP=['pages'=>Page::class,'services'=>Service::class,'courses'=>Course::class];
 private function model(string $resource): string{abort_unless(isset(self::MAP[$resource]),404);return self::MAP[$resource];}
 private function item(string $resource,int $id,BrandContext $ctx):Model{$class=$this->model($resource);$item=$class::where('brand_id',$ctx->id())->findOrFail($id);$this->authorize('view',$item);return $item;}
 private function labels(string $resource):string{return ['pages'=>'頁面','services'=>'服務','courses'=>'課程'][$resource]??'';}
 public function index(string $resource,BrandContext $ctx){$class=$this->model($resource);$this->authorize('viewAny',$class);$query=$class::where('brand_id',$ctx->id());if($resource!=='pages')$query->orderBy('sort_order');return view('admin.content.index',['resource'=>$resource,'label'=>$this->labels($resource),'items'=>$query->orderBy('id')->paginate(20)]);}
 public function create(string $resource){$class=$this->model($resource);$this->authorize('create',$class);return view('admin.content.form',['resource'=>$resource,'label'=>$this->labels($resource),'item'=>new $class]);}
 public function store(Request $r,string $resource,BrandContext $ctx,AuditService $audit){$class=$this->model($resource);$this->authorize('create',$class);$item=$class::create($this->validated($r,$resource,$ctx));$audit->record($resource.'.created',$item,[],$item->toArray(),$ctx->id());return redirect()->route('admin.content.edit',[$resource,$item])->with('status','內容已建立。');}
 public function edit(string $resource,int $id,BrandContext $ctx){$item=$this->item($resource,$id,$ctx);return view('admin.content.form',['resource'=>$resource,'label'=>$this->labels($resource),'item'=>$item]);}
 public function update(Request $r,string $resource,int $id,BrandContext $ctx,AuditService $audit){$item=$this->item($resource,$id,$ctx);$this->authorize('update',$item);$before=$item->toArray();$item->update($this->validated($r,$resource,$ctx,$item));$audit->record($resource.'.updated',$item,$before,$item->fresh()->toArray());return back()->with('status','內容已更新。');}
 public function publish(string $resource,int $id,BrandContext $ctx,AuditService $audit){$item=$this->item($resource,$id,$ctx);$this->authorize('update',$item);$before=$item->toArray();$item->update(['status'=>'published','published_at'=>$item->published_at??now()]);$audit->record($resource.'.published',$item,$before,$item->fresh()->toArray());return back()->with('status','內容已發布。');}
 public function unpublish(string $resource,int $id,BrandContext $ctx,AuditService $audit){$item=$this->item($resource,$id,$ctx);$this->authorize('update',$item);$before=$item->toArray();$item->update(['status'=>'draft']);$audit->record($resource.'.unpublished',$item,$before,$item->fresh()->toArray());return back()->with('status','內容已下架。');}
 public function destroy(string $resource,int $id,BrandContext $ctx,AuditService $audit){$item=$this->item($resource,$id,$ctx);$this->authorize('delete',$item);$audit->record($resource.'.deleted',$item,$item->toArray());$item->delete();return redirect()->route('admin.content.index',$resource)->with('status','內容已刪除。');}
 private function validated(Request $r,string $resource,BrandContext $ctx,?Model $item=null):array{$table=$resource;$name=$resource==='pages'?'title':'name';$rules=[$name=>'required|string|max:160','slug'=>['required','alpha_dash','max:160',Rule::unique($table)->where(fn($q)=>$q->where('brand_id',$ctx->id()))->ignore($item?->id)],'status'=>['required',Rule::in(['draft','published'])],'published_at'=>'nullable|date','seo_title'=>'nullable|string|max:255','seo_description'=>'nullable|string|max:1000'];if($resource==='pages')$rules+=['type'=>['required',Rule::in(['home','about','custom'])],'excerpt'=>'nullable|string|max:1000','body'=>'nullable|string|max:50000'];else $rules+=['summary'=>'nullable|string|max:1000','description'=>'nullable|string|max:50000','sort_order'=>'nullable|integer|min:0|max:9999'];if($resource==='courses')$rules+=['location_note'=>'nullable|string|max:500','duration_minutes'=>'nullable|integer|min:1|max:10080','price_amount'=>'nullable|numeric|min:0|max:99999999','price_note'=>'nullable|string|max:500'];$data=$r->validate($rules);$data['brand_id']=$ctx->id();$data['sort_order']=(int)($data['sort_order']??0);return $data;}
}
